platform :ios, '10.3'
use_frameworks!

target 'DecisionKitchen' do
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'FirebaseUI/Facebook'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'Button', '~> 5'
end
